language: node_js

# Faster container-based builds
sudo: false

node_js:
  - "10"

install:
  - npm install openzeppelin-solidity
  - npm install -g truffle ganache-cli

script:
  - nohup ganache-cli &
  - cd contracts && truffle test
